-- Day 2: 선착순 쿠폰 발급 도메인 초기 스키마
-- 엔티티: User, Coupon, CouponStock(쿠폰당 1행), CouponIssue(1인 1매 unique)
-- 스키마는 이 마이그레이션이 소유하고 Hibernate 는 validate 만 한다(append-only, 수정 금지).

-- 사용자: CouponIssue 가 FK 로 참조하는 최소 엔티티
CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

-- 쿠폰 정책: 이름, 총 발급 한도, 발급 기간
CREATE TABLE coupons (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(200) NOT NULL,
    total_quantity INTEGER      NOT NULL,
    issue_start_at TIMESTAMP    NOT NULL,
    issue_end_at   TIMESTAMP    NOT NULL,
    created_at     TIMESTAMP    NOT NULL,
    CONSTRAINT ck_coupons_total_quantity_positive CHECK (total_quantity > 0)
);

-- 재고: 쿠폰당 1행. 잔여 수량을 행 단위로 추적(Day 4 행 락 대상).
CREATE TABLE coupon_stocks (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id          BIGINT  NOT NULL,
    remaining_quantity INTEGER NOT NULL,
    CONSTRAINT uq_coupon_stocks_coupon UNIQUE (coupon_id),
    CONSTRAINT fk_coupon_stocks_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id),
    CONSTRAINT ck_coupon_stocks_remaining_non_negative CHECK (remaining_quantity >= 0)
);

-- 발급 이력: 누가 어떤 쿠폰을 언제 발급. (coupon_id, user_id) unique 로 1인 1매 보장.
CREATE TABLE coupon_issues (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id  BIGINT    NOT NULL,
    user_id    BIGINT    NOT NULL,
    issued_at  TIMESTAMP NOT NULL,
    CONSTRAINT uq_coupon_issues_coupon_user UNIQUE (coupon_id, user_id),
    CONSTRAINT fk_coupon_issues_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id),
    CONSTRAINT fk_coupon_issues_user FOREIGN KEY (user_id) REFERENCES users (id)
);
